---
title: "Genetic Diversity"
author: "Lia Baumann"
date: "2024-06-04"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Genetic diversity

```{r Tabellen laden, message=FALSE, warning=FALSE, include=FALSE}
library(readxl)
library(knitr)
library(tidyverse)
library(ggplot2)
theme_set(theme_bw())
library(sf)
library(ggspatial)
library(rnaturalearth)
library(envalysis)
library(forcats)
library(poppr)
library(treemap)
library(pegas)
library(adegenet)
library(devtools)
library(hierfstat)
library(mmod)
library(diveRsity)
library(vegan)
T_all <- read_excel("Tuaest_Master_genMonit_haploid_MP_Mai2024.xlsx")
myData <- read.genalex("Daten_Genalex.csv",genclone=TRUE, ploidy=1)
myData_genind <- read.genalex("Daten_Genalex.csv",genclone=FALSE, ploidy=1)
myData_genind_allMarkersOnly <- myData_genind %>%
  missingno("geno", cutoff = 0)
splitStrata(myData) <- ~Pop/Month/SamplingYear/TruffleYear
splitStrata(myData_genind) <- ~Pop/Month/SamplingYear/TruffleYear
splitStrata(myData_genind_allMarkersOnly) <- ~Pop/Month/SamplingYear/TruffleYear
```

Basic stats with hierfstat

```{r basic stats with all data, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
basic.stats(myData_genind)
```
```{r basic stats with reduced dataset (no NAs), message=FALSE, warning=FALSE}
locus_table(myData_genind_allMarkersOnly)
locus_table(myData_genind_aMO_k6_minus3)
```

```{r locus allele frequencies}
allele_freq <- tab(myData_genind_allMarkersOnly, freq = TRUE)
locus_freq <- colMeans(allele_freq)

# Convert to data frame for easier manipulation
allele_freq_df <- as.data.frame(locus_freq)
allele_freq_df <- rownames_to_column(allele_freq_df, var = "Allele")

# Separate locus and allele parts into two columns
allele_freq_df <- allele_freq_df %>%
  separate(Allele, into = c("Locus", "Allele"), sep = "\\.") %>%
  rename("Mean_Frequency" = "locus_freq")

# Calculate mean frequency per locus
overall_mean_per_locus <- allele_freq_df %>%
  group_by(Locus) %>%
  summarize(Overall_Mean_Frequency = mean(Mean_Frequency))

# Combine individual allele frequencies with overall mean per locus
final_table <- allele_freq_df %>%
  left_join(overall_mean_per_locus, by = "Locus")

ggplot(final_table, aes(x = Allele, y = Mean_Frequency, color = Locus)) +
  geom_point(size = 3) +
  geom_hline(aes(yintercept = Overall_Mean_Frequency), 
             data = overall_mean_per_locus, 
             color = "black", linetype = "dashed") +
  facet_wrap(~ Locus, scales = "free_x", ncol = 3) +
  labs(title = "Mean Allele Frequencies by Locus",
       x = "Allele",
       y = "Mean Frequency") +
  theme_minimal() +
  theme(legend.position = "none")

# Separate the genind object by populations
#setPop(myData_genind_allMarkersOnly) <- ~Pop
#populations <- seppop(myData_genind_allMarkersOnly)

# Initialize a list to store allele frequencies for each population
#allele_freq_by_pop <- list()

# Loop over each population and calculate allele frequencies
#for (pop_name in names(populations)) {
  # Calculate allele frequencies for the current population
#  allele_freq <- tab(populations[[pop_name]], freq = TRUE)
  
  # Remove alleles with zero frequency across all individuals in this population
#  allele_freq <- allele_freq[, colSums(allele_freq) > 0]
  
  # Store the filtered allele frequencies in the list
#  allele_freq_by_pop[[pop_name]] <- allele_freq
#}

# Display allele frequencies for each population
#for (pop_name in names(allele_freq_by_pop)) {
#  cat("\nFiltered Allele Frequencies for Population:", pop_name, "\n")
#  print(allele_freq_by_pop[[pop_name]])
#}
```

Basic stats with poppr

```{r basic stats with poppr, message=FALSE, warning=FALSE}
setPop(myData_genind) <- ~Pop
locus_table(myData_genind)
kable(poppr(myData_genind))
```

```{r basic stats with poppr, reduced dataset (no NAs), message=FALSE, warning=FALSE}
setPop(myData_genind_allMarkersOnly) <- ~Pop
kable(locus_table(myData_genind_allMarkersOnly))
poppr_aMO <- as.tibble(poppr(myData_genind_allMarkersOnly))
poppr_aMO

#comparison with Virginie
setPop(myData_genind_allMarkersOnly) <- ~Pop/SamplingYear
subVir <- myData_genind_allMarkersOnly %>%
  popsub(sublist=c("BOH_2013","BOB_2011","UEB_2011","UEB_2013"))
poppr(subVir)
```

```{r rarefaction curve}
setPop(myData_genind) <- ~Pop
summary(myData_genind)
H.Pop <- mlg.table(myData_genind, bar=FALSE)
rarecurve(H.Pop, ylab="Number of expected MLGs", sample=min(rowSums(H.Pop)), border = NA, fill = NA, font = 2, cex = 1, col =1, lty=1)
```
