---
title: "Presentation2024"
author: "Lia Baumann"
date: "2024-07-10"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Nei's Genetic diversity

```{r Tabellen laden, message=FALSE, warning=FALSE, include=FALSE}
library(readxl)
library(knitr)
library(tidyverse)
library(ggplot2)
theme_set(theme_bw())
library(envalysis)
library(forcats)
library(poppr)
library(treemap)
library(pegas)
library(adegenet)
library(devtools)
library(hierfstat)
library(mmod)
library(diveRsity)
library(vegan)
library(writexl)
T_all <- read_excel("Tuaest_Master_genMonit_haploid_MP_Mai2024.xlsx")
myData <- read.genalex("Daten_Genalex.csv",genclone=TRUE, ploidy=1)
myData_genind <- read.genalex("Daten_Genalex.csv",genclone=FALSE, ploidy=1)
myData_genind_allMarkersOnly <- myData_genind %>%
  missingno("geno", cutoff = 0)
splitStrata(myData) <- ~Pop/Month/SamplingYear/TruffleYear
splitStrata(myData_genind) <- ~Pop/Month/SamplingYear/TruffleYear
splitStrata(myData_genind_allMarkersOnly) <- ~Pop/Month/SamplingYear/TruffleYear
```

### myData_genind_allMarkersOnly locus table mean over all data
```{r mean table over all, echo=TRUE, warning=FALSE, message=FALSE}
setPop(myData_genind_allMarkersOnly) <- ~Pop/SamplingYear
locus_table(myData_genind_allMarkersOnly, lev="genotype")
```

### myData_genind_allMarkersOnly locus table per Population (Strata: Population / SamplingYear)
```{r Hexp table Pop SamplingYear, echo=TRUE, warning=FALSE, message=FALSE}
setPop(myData_genind_allMarkersOnly) <- ~Pop/SamplingYear

# create a data frame and transpose the result;
# use sapply to iterate over all populations calculated by seppop.
# then use the locus_table function on the level Genotype

locus_table_SY <- data.frame(t(
  sapply(seppop(myData_genind_allMarkersOnly),
    function(ls) poppr::locus_table(ls,lev="genotype"))))

# choose only the columns corresponding to Hexp values and rename them with their loci

locus_table_SY_hexp <- 
  select(locus_table_SY, X31:X45) %>%
  rename(aest06_1=X31,aest07_1=X32, aest15_1=X33, aest26_1=X34,aest28_1=X35, aest35_1=X36, aest36_1=X37, aest01_1=X38, aest10_1=X39, aest18_1=X40, aest24_1=X41, aest25_1=X42, aest29_1=X43, aest31_1=X44, mean=X45) %>%
  tibble::rownames_to_column("Pop") %>%
  separate(.,Pop,sep="_", into=c("Pop","SamplingYear"))
                                      
#check with one population:
#locus_table(myData_genind_AllMarkersOnly, lev="genotype",population="UEB_2015")
#looks good

kable(locus_table_SY_hexp)
locus_table_SY_hexp_pivot <- pivot_longer(locus_table_SY_hexp,cols=3:16,names_to="locus",values_to="value")

ggplot(locus_table_SY_hexp_pivot,aes(x=as.numeric(SamplingYear), y=value)) +
  geom_point(pch=20) +
  geom_smooth(method="gam", formula=y~s(x,k=2), colour="darkgreen") +
  facet_wrap(vars(Pop)) +
  theme(aspect.ratio=0.35) +
  labs(y="Nei's genetic diversity Hexp", x="Sampling year") +
  ggtitle("Nei's genetic diversity per locus, Sampling year and Population")
```

```{r GAM plots SY, eval=FALSE, include=FALSE}
#calculating the GAM
library(mgcv)

mod_gam = gam(value ~ s(as.numeric(SamplingYear),k=5), data = locus_table_SY_hexp_pivot)
summary(mod_gam)
plot(mod_gam)
plot(value~SamplingYear,data=locus_table_SY_hexp_pivot)

#model <- gam(SI~s(year,k=5),data=mp_BOB_all)   
#summary(model_BOB)
#plot(model_BOB)
#plot (SIR~year,data=mp_BOB_all,pch=16, main = "Bohlingen_Buche")

ax <- seq(2010,2023,length=100)
ay <- predict(mod_gam,list(SamplingYear=ax),type="response",se.fit=T)
matlines(ax,
          cbind(ay$fit,ay$fit+1.96*ay$se.fit,ay$fit-1.96*ay$se.fit),
          lwd=c(2,1,1),lty=c(1,2,2),col=1)
```


### myData_genind_allMarkersOnly locus table per Population (Strata: Population / TruffleYear)
```{r Hexp table Pop TruffleYear, echo=TRUE, warning=FALSE, message=FALSE}
setPop(myData_genind_allMarkersOnly) <- ~Pop/TruffleYear

# create a data frame and transpose the result;
# use sapply to iterate over all populations calculated by seppop.
# then use the locus_table function on the level Genotype

locus_table_TY <- data.frame(t(
  sapply(seppop(myData_genind_allMarkersOnly),
    function(ls) poppr::locus_table(ls,lev="genotype"))))

# choose only the columns corresponding to Hexp values and rename them with their loci

locus_table_TY_hexp <- 
  select(locus_table_TY, X31:X45) %>%
  rename(aest06_1=X31,aest07_1=X32, aest15_1=X33, aest26_1=X34,aest28_1=X35, aest35_1=X36, aest36_1=X37, aest01_1=X38, aest10_1=X39, aest18_1=X40, aest24_1=X41, aest25_1=X42, aest29_1=X43, aest31_1=X44, mean=X45) %>%
    tibble::rownames_to_column("Pop") %>%
  separate(.,Pop,sep="_", into=c("Pop","TruffleYear"))
                                      
#check with one population:
#locus_table(myData_genind_AllMarkersOnly, lev="genotype",population="UEB_2015")
#looks good

kable(locus_table_TY_hexp)

ggplot(locus_table_TY_hexp,aes(x=TruffleYear, y=mean)) +
  geom_point() +
  facet_wrap(vars(Pop))
```

```{r write excel files}
write_xlsx(locus_table_SY_hexp, "C:\\Users\\liaba\\OneDrive - Eidg. Forschungsanstalt WSL\\R\\truffles\\Presentation-Summer-24_files\\locus_table_SY_hexp.xlsx")
write_xlsx(locus_table_TY_hexp, "C:\\Users\\liaba\\OneDrive - Eidg. Forschungsanstalt WSL\\R\\truffles\\Presentation-Summer-24_files\\locus_table_TY_hexp.xlsx")
```

# Rarefaction of Neis' diversity index
Rarefied: Hexp * (N/N-1). N= Anzahl samples (nicht Allele)

```{r rarefy Nei SamplingYear}
setPop(myData_genind_allMarkersOnly) <- ~Pop/SamplingYear
popdata_pop_year_rareNei_SY <- poppr(myData_genind_allMarkersOnly) %>%
  select(Pop, N)

locus_table_SY_hexp_N <- 
  select(locus_table_SY, X31:X45) %>%
  rename(aest06_1=X31,aest07_1=X32, aest15_1=X33, aest26_1=X34,aest28_1=X35, aest35_1=X36, aest36_1=X37, aest01_1=X38, aest10_1=X39, aest18_1=X40, aest24_1=X41, aest25_1=X42, aest29_1=X43, aest31_1=X44, mean=X45) %>%
    tibble::rownames_to_column("Pop") %>%
  left_join(.,popdata_pop_year_rareNei_SY,by="Pop") %>%
  separate(.,Pop,sep="_", into=c("Pop","SamplingYear"))

N <- locus_table_SY_hexp_N$N #number of samples
#calculate rarefaction over all the values (columns 3:17)
rarHexpSY <- (N/(N-1))*select(locus_table_SY_hexp_N,3:17)
#add the pop and year again
rarHexpSY <- bind_cols(rarHexpSY,Pop = locus_table_SY_hexp_N$Pop, SamplingYear = locus_table_SY_hexp_N$SamplingYear)

kable(rarHexpSY)

```

```{r rarefy Nei TruffleYear}
setPop(myData_genind_allMarkersOnly) <- ~Pop/TruffleYear
popdata_pop_year_rareNei_TY <- poppr(myData_genind_allMarkersOnly) %>%
  select(Pop, N)

locus_table_TY_hexp_N <- 
  select(locus_table_TY, X31:X45) %>%
  rename(aest06_1=X31,aest07_1=X32, aest15_1=X33, aest26_1=X34,aest28_1=X35, aest35_1=X36, aest36_1=X37, aest01_1=X38, aest10_1=X39, aest18_1=X40, aest24_1=X41, aest25_1=X42, aest29_1=X43, aest31_1=X44, mean=X45) %>%
    tibble::rownames_to_column("Pop") %>%
  left_join(.,popdata_pop_year_rareNei_TY,by="Pop") %>%
  separate(.,Pop,sep="_", into=c("Pop","TruffleYear"))

N <- locus_table_TY_hexp_N$N #number of samples
#calculate rarefaction over all the values (columns 3:17)
rarHexpTY <- (N/(N-1))*select(locus_table_TY_hexp_N,3:17)
#add the pop and year again
rarHexpTY <- bind_cols(rarHexpTY,Pop = locus_table_TY_hexp_N$Pop, TruffleYear = locus_table_TY_hexp_N$TruffleYear)

kable(rarHexpTY)

```


```{r write excel files rarefied}
write_xlsx(rarHexpSY, "C:\\Users\\liaba\\OneDrive - Eidg. Forschungsanstalt WSL\\R\\truffles\\Presentation-Summer-24_files\\rarHexpSY.xlsx")
write_xlsx(rarHexpTY, "C:\\Users\\liaba\\OneDrive - Eidg. Forschungsanstalt WSL\\R\\truffles\\Presentation-Summer-24_files\\rarHexpTY.xlsx")
```

# PCA

```{r pca, echo=TRUE}
#uncorrected PCA with allMarkersOnly dataset
setPop(myData_genind_allMarkersOnly) <- ~Pop
x.pops_allMarkersOnly <- tab(myData_genind_allMarkersOnly,
                             freq=TRUE, NA.method="mean")
#x.pops_allMarkersOnly[grep("FRE", rownames(x.pops_allMarkersOnly)), ]

pca.pops.allMarkersOnly <- dudi.pca(df = x.pops_allMarkersOnly,
                                    center = TRUE, scale = FALSE, scannf = FALSE, nf = 2)

s.class(pca.pops.allMarkersOnly$li, fac=pop(myData_genind_allMarkersOnly),
        col=funky(15),
        sub="PCA mit Datenset ohne NA (allMarkersOnly)")

#clonecorrected PCA  with samplingYear
cc_myData_genind_allMarkersOnly_SY <- clonecorrect(myData_genind_allMarkersOnly,
                                                   strata=~Pop/SamplingYear)
x.pops_cc.SY <- tab(cc_myData_genind_allMarkersOnly_SY,
                    freq=TRUE, NA.method="mean")
pca.pops_cc.SY <- dudi.pca(df = x.pops_cc.SY,
                           center = TRUE, scale = FALSE, scannf = FALSE, nf = 2)
s.class(pca.pops_cc.SY$li,
        fac=pop(cc_myData_genind_allMarkersOnly_SY),
        col=funky(15),
        sub="PCA mit poppr klonkorrigiertem Datenset ohne NA (allMarkersOnly)")

#clonecorrected PCA  with TruffleYear
cc_myData_genind_allMarkersOnly_TY <- clonecorrect(myData_genind_allMarkersOnly,
                                                   strata=~Pop/TruffleYear)
x.pops_cc.TY <- tab(cc_myData_genind_allMarkersOnly_TY,
                    freq=TRUE, NA.method="mean")
pca.pops_cc.TY <- dudi.pca(df = x.pops_cc.TY,
                           center = TRUE, scale = FALSE, scannf = FALSE, nf = 2)
s.class(pca.pops_cc.TY$li,
        fac=pop(cc_myData_genind_allMarkersOnly_TY),
        col=funky(15))
```